---
Name: elemental-textcontentforsearch
---
DNADesign\Elemental\Models\BaseElement:
  extensions:
    textSearchExtension: DNADesign\Elemental\Extensions\BaseElementTextSearchExtension
  exclude_fields_from_search:
    - ExtraClass
    - Style

DNADesign\Elemental\Models\ElementalArea:
  extensions:
    textSearchExtension: DNADesign\Elemental\Extensions\ElementalAreaTextSearchExtension